### ISSUE TITLE
[Preprints] Need a comment moderation queue and Preprint Manager dashboard indicator

### ISSUE THREAD

**Issue by justingonder** [openlibhums/janeway#1771] opened 2020-08-12 18:47 UTC
**Is your feature request related to a problem? Please describe.**
Currently, comments made in the repository await moderation before appearing on the public site, but there is no way to see all of the comments that need moderation in one place. Instead, a user must currently navigate to an individual article, see that comments are awaiting moderation, and attend to them.

**Describe the solution you'd like**
There should be a count of comments awaiting moderation in the Preprints Stats area of the Preprint Manager dashboard. Clicking on that count should lead a user to some interface for moderating pending comments (e.g. a list of articles with pending comments and a count, or perhaps just a list of the comments awaiting moderation with quick approve / decline action buttons)

**Comment by justingonder** [comment] 2020-08-24 15:29
let me run this by the EA folks to make sure i get it right.

**Comment by hardyoyo** [comment] 2024-06-10 21:16
See also #3255, probably a duplicate?

**Comment by mauromsl** [comment] 2024-09-26 10:43
Dupe of #3255

**Closed by mauromsl** 2024-09-26 10:43 UTC
Labels: new feature, preprints
