### ISSUE TITLE
Select all/none for article facets

### ISSUE THREAD

**Issue by hinefuku** [openlibhums/janeway#1132] opened 2019-05-16 14:28 UTC
**Describe the solution you'd like**
On the Articles page, a select all/none option for the facet filters would be useful.

**Comment by ajrbyers** [comment] 2024-11-14 11:37
There is a clear all button now, so closing this as a duplicate of:

https://github.com/openlibhums/janeway/issues/2097

**Closed by ajrbyers** 2024-11-14 11:37 UTC
Labels: new feature, size M, dev-ready
